config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  get "home", to: "static_pages#home"
  get "reviews", to: "static_pages#reviews"
  get "categories", to: "static_pages#categories"
  get "contact", to: "static_pages#contact"

  devise_for :users

  # Creates all CRUD routes for blog_posts entity
  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
    resources :comments, only: [:create, :destroy]
  end

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content
  has_many :comments, dependent: :destroy
  belongs_to :author, class_name: "User"

  validates :title, presence: true
  validates :content, presence: true

  # scope :sorted, -> { order(Arel.sql("published_at DESC NULLS FIRST")).order(updated_at: :desc) } --> another option how to ensure sorting
  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog_post
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable, :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :blog_posts, foreign_key: "author_id", dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  def authenticate_admin!
    authenticate_user!
    redirect_to root_path, alert: "You are not authorized to access this page." unless current_user.admin?
  end
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_admin!
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge_later
    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove( dom_id(@blog_post, :cover_image)) }
    end
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy] # only: [...] is opposite to except: [...]
  def index
    @blog_posts = current_user&.admin? ? BlogPost.sorted: BlogPost.published.sorted
    @pagy, @blog_posts = pagy(@blog_posts)
  rescue Pagy::OverflowError
    redirect_to root_path(page: 1)
    # another option to replace line above:
    # params[:page] = 1
    # retry
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    @blog_post.author = current_user
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :cover_image, :content, :published_at, :author_id)
  end

  def set_blog_post
    @blog_post = current_user&.admin? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @blog_post = BlogPost.find(params[:blog_post_id])
    @comment = @blog_post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @blog_post, notice: 'Comment created!'
    else
      redirect_to @blog_post, alert: 'Comment could not be created!'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    if @comment.user == current_user or current_user.admin?
      @comment.destroy
      redirect_to @comment.blog_post, notice: 'Comment was successfully deleted.'
    else
      redirect_to @comment.blog_post, alert: 'You are not authorized to delete this comment.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def reviews
  end

  def categories
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def gravatar_for(user, options = { size: 100, class: "gravatar" })
    return unless user.present? && user.email.present?

    email_hash = Digest::MD5.hexdigest(user.email.downcase.strip)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{email_hash}?s=#{size}"

    image_tag(gravatar_url, alt: user.email, class: options[:class])
  end

  def full_title(page_title = '')
    base_title = "Blog Sample"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :cover_image %>
    <%= form.file_field :cover_image %>
  </div>
  <% if blog_post.cover_image.present? %>
    <div id="<%= dom_id(blog_post, :cover_image) %>">
      <%= image_tag blog_post.cover_image %>
      <%= link_to "Remove cover image", blog_post_cover_image_path(blog_post),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete cover image"} %>
    </div>
  <% end %>
  <div>
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>
  <div>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_blank: true %>
  </div>
  <div>
    <%= form.button %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<% provide(:title, "Edit Post") %>
<h1> Edit Blog Post </h1>

<%= render partial: "form", locals: {blog_post: @blog_post}%>

<%= button_to "Delete", blog_post_path(@blog_post), method: :delete, data: {turbo_confirm: "Are you sure you want to delete this blog post?"}%>

app/views/blog_posts/index.html.erb
<% provide(:title, "All Posts") %>

<div class="container">
  <h2 class="title section-title" data-name="Blog posts"> Blog posts </h2>

  <% @blog_posts.each do |blog_post| %>
    <a href="<%= blog_post_path(blog_post.id) %>" class="trending-news-box">
      <!-- blog_post_path(blog_post.id) = blog_post_path(blog_post) = blog_post -->

      <div class="trending-news-image-box">
        <span class="trending-number place-items-center"><%= blog_post.id %></span>
        <%= image_tag blog_post.cover_image, class: "article-image" %>
        <%#= image_tag blog_post.cover_image if blog_post.cover_image.present? %>
      </div>

      <div class="trending-news-data">
        <div class="article-data">
          <span> <%= blog_post.published_at %> </span>
          <span class="article-data-spacer"></span>
          <span> estimated read time </span>

          <h3 class="title article-title"> <%= blog_post.title %> </h3>
        </div>
      </div>
    </a>

    <% if blog_post.draft? %>
      <div style="background-color: darkgray; color: dimgrey; height: 50px; width: 150px; align-items: center; justify-content: center; display: flex; border-radius: 12px; font-size: 24px"> Draft </div>
    <% elsif blog_post.scheduled? %>
      <div style="background-color: lightskyblue; color: dodgerblue; height: 50px; width: 150px; align-items: center; justify-content: center; display: flex; border-radius: 12px; font-size: 24px"> Scheduled </div>
    <% end %>

  <% end %>

  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/blog_posts/new.html.erb
<% provide(:title, "New Post") %>
<h1> New Blog Post </h1>

<%= render partial: "form", locals: {blog_post: @blog_post}%>

app/views/blog_posts/show.html.erb
<section class="blog-post section-header-offset">

  <div class="blog-post-container container">

    <div class="blog-post-data">
      <h3 class="title blog-post-title"><%=@blog_post.title %></h3>

      <div class="article-data">

        <span><%=@blog_post.published_at %></span>
        <span class="article-data-spacer"></span>
        <span>estimated read time</span>

        <% if current_user&.admin? %>
          <span class="article-data-spacer"></span>
          <%= link_to "Edit post", edit_blog_post_path(@blog_post) if user_signed_in? %>
        <% end %>
      </div>

      <%= image_tag @blog_post.cover_image if @blog_post.cover_image.present? %>
    </div>

    <div class="container">
      <p><%=@blog_post.content %></p>
    </div>

    <div class="author d-grid">

      <div class="author-image-box">
        <%= gravatar_for(@blog_post.author, size: 500, class: "article-image")%>
      </div>

      <div class="author-about">
        <h3 class="author-name"> <%= @blog_post.author.email %> </h3>
        <p> Something interesting about author of the current article. Something interesting about author of the current article. </p>
      </div>
    </div>
  </div>
</section>

<% if @blog_post.published? %>
  <h2>Comments: </h2>
  <% @blog_post.comments.each do |comment| %>
    <p>
      <strong>
        <%= comment.user.email %><%= comment.user.admin? ? " (Admin)" : "" %>:
      </strong>
      <%= comment.body %>
    </p>
    <% if user_signed_in? && (comment.user == current_user || current_user&.admin?) %>
      <%= link_to 'Delete', [@blog_post, comment],
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this comment?" } %>
    <% end %>
    <!--  blog_post_comment_path(comment.blog_post, comment) equals to [@blog_post, comment] -->
  <% end %>

  <% if user_signed_in? %>
    <%= form_for [@blog_post, Comment.new] do |f| %>
      <div>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
      </div>
      <div>
        <%= f.button "Add Comment" %>
      </div>
    <% end %>
  <% else %>
    <p>You need to <%= link_to 'log in', new_user_session_path %> to comment.</p>
  <% end %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang=en>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Remix Icons via CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css">

    <!-- Swiper CSS and JS via CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Flash messages for Devise gem -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/header" %>

    <div class="section-header-offset">
      <%= yield %>
    </div>

    <%= render "shared/newsletter" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer section">
  <div class="footer-container container d-grid">
    <div class="company-data">
      <%= link_to "BlogSample", root_path, class: "logo" %>

      <p class="company-description"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique a tempore sapiente corporis, eaque fuga placeat odit voluptatibus. </p>

      <ul class="list social-media">

        <li class="list-item">
          <a href="#" class="list-link">
            <i class="ri-instagram-line"></i>
          </a>
        </li>

        <li class="list-item">
          <a href="#" class="list-link">
            <i class="ri-facebook-circle-line"></i>
          </a>
        </li>

        <li class="list-item">
          <a href="#" class="list-link">
            <i class="ri-github-line"></i>
          </a>
        </li>

        <li class="list-item">
          <a href="#" class="list-link">
            <i class="ri-linkedin-line"></i>
          </a>
        </li>

      </ul>

      <span class="copyright-notice">&copy; 2025 BlogSample. All rights reserved.</span>
    </div>

    <div>
      <h6 class="title footer-title"> Categories </h6>
      <ul class="list footer-list">

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>
      </ul>
    </div>

    <div>
      <h6 class="title footer-title"> Company </h6>
      <ul class="list footer-list">

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>
      </ul>
    </div>

    <div>
      <h6 class="title footer-title"> Useful links </h6>
      <ul class="list footer-list">

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>

        <li class="list-title">
          <a class="list-link"> Sample item </a>
        </li>
      </ul>
    </div>

  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header" id="header">
  <nav class="navbar container">
    <a href="<%=root_path%>" class="logo">BlogSample</a>

    <div class="menu" id="menu">
      <ul class="list">
        <li class="list-item">
          <a href="<%=root_path%>" class="list-link current">Home</a>
        </li>
        <li class="list-item">
          <a href="<%=blog_posts_path%>" class="list-link">Articles</a>
        </li>
        <li class="list-item">
          <a href="<%=categories_path%>" class="list-link">Categories</a>
        </li>
        <li class="list-item">
          <a href="<%=contact_path%>" class="list-link">Contact</a>
        </li>

        <%if user_signed_in?%>

          <% if current_user.admin? %>
            <li class="list-item">
              <a href="<%=new_blog_post_path%>" class="list-link">New post</a>
            </li>
          <%end %>

          <li class="list-item">
            <a href="<%=edit_user_registration_path%>" class="list-link">Profile</a>
          </li>

          <li class="list-item">
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "list-link" %>
          </li>
        <% else %>

          <li class="list-item">
            <a href="<%=new_user_session_path%>" class="list-link screen-lg-hidden">Log in</a>
          </li>

          <li class="list-item">
            <a href="<%=new_user_registration_path%>" class="list-link screen-lg-hidden">Sign up</a>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="list list-right">
      <button class="btn place-items-center" id="theme-toggle-btn">
        <i class="ri-sun-line sun-icon"></i>
        <i class="ri-moon-line moon-icon"></i>
      </button>

      <button class="btn place-items-center" id="search-icon">
        <i class="ri-search-line"></i>
      </button>

      <button class="btn place-items-center screen-lg-hidden menu-toggle-icon" id="menu-toggle-icon">
        <i class="ri-menu-3-line open-menu-icon"></i>
        <i class="ri-close-line close-menu-icon"></i>
      </button>

      <% if not user_signed_in? %>
        <a href="<%=new_user_session_path%>" class="list-link screen-sm-hidden">Log in</a>
        <a href="<%=new_user_registration_path%>" class="btn sign-up-btn fancy-border screen-sm-hidden">
          <span>Sign up</span>
        </a>
      <% end %>

    </div>
  </nav>
</header>

<div class="search-form-container container" id="search-form-container">

  <div class="form-container-inner">
    <form action="" class="form">
      <input type=text class="form-input" placeholder="What are looking for?">
      <button class="btn form-btn" type="submit">
        <i class="ri-search-line"></i>
      </button>
    </form>
    <span class="form-note"> Or press ESC to close. </span>
  </div>

  <button class="btn form-close-btn place-items-center" id="form-close-btn">
    <i class="ri-close-line"></i>
  </button>
</div>

app/views/shared/_newsletter.html.erb
<section class="newsletter-section">
  <div class="container">

    <h2 class="title section-title" data-name="Newsletter"> Newsletter </h2>

    <div class="form-container-inner">

      <h6 class="title newsletter-title"> Subscribe to BlogSample </h6>
      <p class="newsletter-description"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique a tempore sapiente corporis, eaque fuga placeat odit voluptatibus. </p>

      <form action="#" class="form">
        <input type="text" class="form-input" placeholder="Enter your email address">
        <button class="btn  form-btn" type="submit">
          <i class="ri-mail-send-line"></i>
        </button>
      </form>

    </div>
  </div>
</section>

app/views/static_pages/categories.html.erb
<% provide(:title, "Categories") %>
<h1>Blog Sample App</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Blog Sample App</h1>

app/views/static_pages/reviews.html.erb
<% provide(:title, "Reviews") %>
<h1>Blog Sample App</h1>